baseurl = "https://hsherl.github.io/"
publishDir = "docs"
languageCode = "en-gb"
title = "Henrik RÃ¸ed Sherling"
theme = "hsherl"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    identifier = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Teaching"
    identifier = "teaching"
    url = "/teaching/"
    weight = 3
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/projects/"
    weight = 2

[params]
    description = "Henrik Sherling's academic website."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "suit-profile.png"
    width = 50
    height = 50
    alt = "Profile picture, October 2020"
